class Lamini:
    def __init__(self, model_name):
        if model_name == "meta-llama/Meta-Llama-3-8B-Instruct":
            self.responses = {
                "<|begin_of_text|><|start_header_id|>system<|end_header_id|>\n\nYou are a helpful assistant.<|eot_id|><|start_header_id|>user<|end_header_id|>\n\nPlease write a birthday card for my good friend Andrew<|eot_id|><|start_header_id|>assistant<|end_header_id|>\n\n": "Here's a birthday card message for your friend Andrew:\n\n\"Happy birthday to an amazing friend like you, Andrew!\n\nOn your special day and always, I want you to know how much you mean to me. You bring so much joy, laughter, and adventure into my life, and I'm grateful for our friendship every day.\n\nHere's to another year of making unforgettable memories, trying new things, and creating more inside jokes. You deserve all the best, and I hope your birthday is as awesome as you are!\n\nCheers to you, my friend! \"\n\nFeel free to modify it as you see fit, and I hope Andrew loves it!",
                "<|begin_of_text|><|start_header_id|>user<|end_header_id|>\n\nTell me a joke about birthday cake<|eot_id|><|start_header_id|>assistant<|end_header_id|>\n\n": "Why was the birthday cake in a bad mood?\n\nBecause it was feeling crumby!",
                "<|begin_of_text|><|start_header_id|>user<|end_header_id|>\n\nGiven an arbitrary table named `sql_table`, write a query to return how many rows are in the table.<|eot_id|><|start_header_id|>assistant<|end_header_id|>\n\n": "The query to return the number of rows in a table named `sql_table` is:\n\n```sql\nSELECT COUNT(*) \nFROM sql_table;\n```\n\nThis query uses the `COUNT(*)` function to count the number of rows in the table. The `*` is a wildcard that means \"all columns\", but in this case, we don't need to specify any specific columns because we're only interested in counting the number of rows.",
                "<|begin_of_text|><|start_header_id|>user<|end_header_id|>\n\nGiven an arbitrary table named `sql_table`, \nhelp me calculate the average `height` where `age` is above 20.<|eot_id|><|start_header_id|>assistant<|end_header_id|>\n\n": "Assuming you are using SQL, you can use the following query to calculate the average `height` where `age` is above 20:\n\n```sql\nSELECT AVG(height) \nFROM sql_table \nWHERE age > 20;\n```\n\nThis query will return the average `height` for all rows in `sql_table` where the `age` is greater than 20.",
                "<|begin_of_text|><|start_header_id|>user<|end_header_id|>\n\nGiven an arbitrary table named `sql_table`, \nCan you calculate the p95 `height` where the `age` is above 20?<|eot_id|><|start_header_id|>assistant<|end_header_id|>\n\n": "Assuming you are using a SQL database, you can use the following query to calculate the 95th percentile of the `height` column where the `age` is above 20:\n\n```sql\nSELECT PERCENTILE_CONT(0.95) WITHIN GROUP (ORDER BY height) \nFROM sql_table \nWHERE age > 20;\n```\n\nThis query uses the `PERCENTILE_CONT` function to calculate the 95th percentile of the `height` column. The `WITHIN GROUP (ORDER BY height)` clause specifies that the percentile should be calculated within the group of rows ordered by the `height` column. The `WHERE age > 20` clause filters the rows to only include those where the `age` is above 20.\n\nNote that the exact syntax may vary depending on the specific database management system you are using. For example, in MySQL, you would use `PERCENTILE_CONT(0.95) WITHIN GROUP (ORDER BY height) OVER",
                "<|begin_of_text|><|start_header_id|>user<|end_header_id|>\n\nGiven an arbitrary table named `sql_table`, Can you calculate the p95 `height` where the `age` is above 20? Use sqlite.<|eot_id|><|start_header_id|>assistant<|end_header_id|>\n\n": "You can use the following SQL query to calculate the 95th percentile of the `height` column where the `age` is above 20:\n```\nSELECT PERCENTILE(height) WITHIN GROUP (ORDER BY height) AS p95_height\nFROM sql_table\nWHERE age > 20;\n```\nThis query uses the `PERCENTILE` function to calculate the 95th percentile of the `height` column, and the `WITHIN GROUP` clause to specify that the percentile should be calculated within the group of rows where `age` is greater than 20.\n\nNote that the `PERCENTILE` function is only available in SQLite 3.25 and later versions. If you are using an earlier version of SQLite, you can use the `NTILE` function instead:\n```\nSELECT NTILE(100, height) AS p95_height\nFROM (\n  SELECT height\n  FROM sql_table\n  WHERE age > 20\n) AS subquery\nORDER",
            }
        else:
            raise ValueError("Invalid model. Please stick to the notebook example.")

    def generate(self, prompt, max_new_tokens=100):
        return self.responses.get(
            prompt,
            "Sorry, I don't know how to respond to that. Please stick to the notebook example.",
        )
